// products related actions //
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_PRODUCT_DETAIL = "GET_PRODUCT_DETAIL";
export const SET_LOADING = "SET_LOADING";

export const SET_ERRORS = "SET_ERRORS";

export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const FETCH_PROFILE_DETAIL = "FETCH_PROFILE_DETAIL";
export const PROFILE_UPDATE = "PROFILE_UPDATE";
export const SET_PROFILE_LOADING = "SET_PROFILE_LOADING";

export const FETCH_ORDER_DETAIL = "FETCH_ORDER_DETAIL";

export const GET_USER_ORDERS = "GET_USER_ORDERS";
export const GET_USER_CART_ORDER = "GET_USER_CART_ORDER";
export const CREATE_ORDER = "CREATE_ORDER";
export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const DELETE_CART_PRODUCT = "DELETE_CART_PRODUCT";
export const ORDER_CHECKOUT = "ORDER_CHECKOUT";

export const GET_USER_CART = "GET_USER_CART";
